// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Approve from '../src/commands/approve.js'
import Changelog from '../src/commands/changelog.js'
import Configure from '../src/commands/configure.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['approve', 'changelog', 'configure'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'approve': Approve,
  'changelog': Changelog,
  'configure': Configure
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'approve': {
      name: 'approve',
      description: 'Approve pending Azure DevOps pipeline approvals',
      options: {
        'pipeline': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Pipeline name filter', short: 'p', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'run': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Run ID filter', short: 'r', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'id': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Approval ID', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'all': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Approve all matched approvals', short: 'a', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":901,"end":906,"loc":{"start":{"line":28,"column":43,"index":901},"end":{"line":28,"column":48,"index":906}},"value":false}}]}, validator: '(val) => true' },
        'comment': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Approval comment', short: 'c', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1150,"end":1155,"loc":{"start":{"line":36,"column":44,"index":1150},"end":{"line":36,"column":49,"index":1155}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/approve'
    },
  'changelog': {
      name: 'changelog',
      description: 'Build release changelog from remote master commits',
      options: {
        'pipeline': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Pipeline name', short: 'p', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'from': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'From run ID override (defaults to latest prod-success run on master)', short: 'f', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'to': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'To commit SHA override (default: latest successful master pipeline run)', short: 't', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'area': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Area filter from predefined configs', short: 'a', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'no-copy': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print only, do not copy changelog to clipboard', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1754,"end":1759,"loc":{"start":{"line":52,"column":49,"index":1754},"end":{"line":52,"column":54,"index":1759}},"value":false}}]}, validator: '(val) => true' },
        'post-webhook': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Post changelog to Microsoft Teams incoming webhook URL', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'channel': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Named Teams channel from release config', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":2151,"end":2156,"loc":{"start":{"line":61,"column":44,"index":2151},"end":{"line":61,"column":49,"index":2156}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/changelog'
    },
  'configure': {
      name: 'configure',
      description: 'Configure release defaults and Teams channels',
      options: {
        'show': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Show current release config', short: 's', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1055,"end":1060,"loc":{"start":{"line":34,"column":44,"index":1055},"end":{"line":34,"column":49,"index":1060}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/configure'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
