// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Comments from '../src/commands/comments.js'
import Copy from '../src/commands/copy.js'
import Create from '../src/commands/create.js'
import List from '../src/commands/list.js'
import Open from '../src/commands/open.js'
import Show from '../src/commands/show.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['comments', 'copy', 'create', 'list', 'open', 'show'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'comments': Comments,
  'copy': Copy,
  'create': Create,
  'list': List,
  'open': Open,
  'show': Show
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'comments': {
      name: 'comments',
      description: 'List pull request review comments',
      options: {
        'id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Pull request ID/number override', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":650,"end":655,"loc":{"start":{"line":16,"column":44,"index":650},"end":{"line":16,"column":49,"index":655}},"value":false}}]}, validator: '(val) => true' },
        'branch': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Branch override for PR auto-detection', short: 'b', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'repo': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Repo override (GitHub: owner/repo, AzDO: repo name)', short: 'r', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
      },
      path: './src/commands/comments'
    },
  'copy': {
      name: 'copy',
      description: 'Copy PR reference with link to clipboard',
      options: {
        'id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Pull request ID/number override', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'branch': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Branch override for PR lookup', short: 'b', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'repo': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Repo override (GitHub: owner/repo, AzDO: repo name)', short: 'r', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1097,"end":1102,"loc":{"start":{"line":31,"column":44,"index":1097},"end":{"line":31,"column":49,"index":1102}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/copy'
    },
  'create': {
      name: 'create',
      description: 'Create a pull request (with auto-complete on)',
      path: './src/commands/create'
    },
  'list': {
      name: 'list',
      description: 'List open pull requests',
      options: {
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1334,"end":1339,"loc":{"start":{"line":68,"column":44,"index":1334},"end":{"line":68,"column":49,"index":1339}},"value":false}}]}, validator: '(val) => true' },
        'all': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Search across all repos', short: 'a', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1463,"end":1468,"loc":{"start":{"line":72,"column":43,"index":1463},"end":{"line":72,"column":48,"index":1468}},"value":false}}]}, validator: '(val) => true' },
        'reviewer': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Show PRs where I am a reviewer', short: 'r', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1593,"end":1598,"loc":{"start":{"line":76,"column":48,"index":1593},"end":{"line":76,"column":53,"index":1598}},"value":false}}]}, validator: '(val) => true' },
        'top': { type: 'z.coerce.number.int.positive.default', required: true, hasDefault: true, default: 50, description: 'Maximum number of PRs to fetch', short: 't', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1741,"end":1743,"loc":{"start":{"line":80,"column":59,"index":1741},"end":{"line":80,"column":61,"index":1743}},"extra":{"rawValue":50,"raw":"50"},"value":50}}]}, validator: '(val) => true' }
      },
      path: './src/commands/list'
    },
  'open': {
      name: 'open',
      description: 'Open pull request for current branch',
      options: {
        'id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Pull request ID/number override', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'branch': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Branch override for PR lookup', short: 'b', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'repo': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Repo override (GitHub: owner/repo, AzDO: repo name)', short: 'r', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
      },
      path: './src/commands/open'
    },
  'show': {
      name: 'show',
      description: 'Show PR merge readiness details',
      options: {
        'id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Pull request ID/number override', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'branch': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Branch override for PR lookup', short: 'b', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'repo': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Repo override (GitHub: owner/repo, AzDO: repo name)', short: 'r', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1444,"end":1449,"loc":{"start":{"line":41,"column":44,"index":1444},"end":{"line":41,"column":49,"index":1449}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/show'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
