// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import List from '../src/commands/list.js'
import Open from '../src/commands/open.js'
import Runs from '../src/commands/runs.js'
import Show from '../src/commands/show.js'
import Trigger from '../src/commands/trigger.js'
import Watch from '../src/commands/watch.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['list', 'open', 'runs', 'show', 'trigger', 'watch'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'list': List,
  'open': Open,
  'runs': Runs,
  'show': Show,
  'trigger': Trigger,
  'watch': Watch
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'list': {
      name: 'list',
      description: 'List pipelines, optionally filtered by glob',
      options: {
        'filter': { type: 'z.array.default', required: true, hasDefault: true, default: undefined, description: 'Glob filter on pipeline name (repeatable)', short: 'f', isArray: true, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"ArrayExpression","start":411,"end":413,"loc":{"start":{"line":17,"column":47,"index":411},"end":{"line":17,"column":49,"index":413}},"elements":[]}}]}, validator: '(val) => true' },
        'top': { type: 'z.coerce.number.int.positive.default', required: true, hasDefault: true, default: 1000, description: 'Maximum number of pipelines to fetch', short: 'n', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":567,"end":571,"loc":{"start":{"line":21,"column":59,"index":567},"end":{"line":21,"column":63,"index":571}},"extra":{"rawValue":1000,"raw":"1000"},"value":1000}}]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":705,"end":710,"loc":{"start":{"line":25,"column":44,"index":705},"end":{"line":25,"column":49,"index":710}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/list'
    },
  'open': {
      name: 'open',
      description: 'Open a pipeline run in browser',
      options: {
        'id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Run ID (opens latest for repo when omitted)', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":498,"end":503,"loc":{"start":{"line":13,"column":44,"index":498},"end":{"line":13,"column":49,"index":503}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/open'
    },
  'runs': {
      name: 'runs',
      description: 'List recent pipeline runs for this repository',
      options: {
        'top': { type: 'z.coerce.number.int.positive.default', required: true, hasDefault: true, default: 10, description: 'Maximum number of runs to print', short: 'n', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":470,"end":472,"loc":{"start":{"line":20,"column":59,"index":470},"end":{"line":20,"column":61,"index":472}},"extra":{"rawValue":10,"raw":"10"},"value":10}}]}, validator: '(val) => true' },
        'all': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Include runs from all repositories', short: 'a', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":600,"end":605,"loc":{"start":{"line":24,"column":43,"index":600},"end":{"line":24,"column":48,"index":605}},"value":false}}]}, validator: '(val) => true' },
        'branch': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Filter by branch', short: 'b', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'result': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Filter by result (succeeded/failed/canceled)', short: 'r', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'status': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Filter by status (inProgress/completed/notStarted)', short: 's', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1147,"end":1152,"loc":{"start":{"line":40,"column":44,"index":1147},"end":{"line":40,"column":49,"index":1152}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/runs'
    },
  'show': {
      name: 'show',
      description: 'Show details for a pipeline run',
      options: {
        'id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Pipeline run ID', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":573,"end":578,"loc":{"start":{"line":24,"column":44,"index":573},"end":{"line":24,"column":49,"index":578}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/show'
    },
  'trigger': {
      name: 'trigger',
      description: 'Queue a new pipeline run',
      options: {
        'id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Pipeline definition ID', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'name': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Pipeline definition name', short: 'm', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'branch': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Branch name or full ref', short: 'b', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'parameter': { type: 'z.array.default', required: true, hasDefault: true, default: undefined, description: 'Pipeline parameter key=value (repeatable)', short: 'p', isArray: true, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"ArrayExpression","start":815,"end":817,"loc":{"start":{"line":31,"column":50,"index":815},"end":{"line":31,"column":52,"index":817}},"elements":[]}}]}, validator: '(val) => true' },
        'variable': { type: 'z.array.default', required: true, hasDefault: true, default: undefined, description: 'Pipeline variable key=value (repeatable)', short: 'v', isArray: true, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"ArrayExpression","start":961,"end":963,"loc":{"start":{"line":35,"column":49,"index":961},"end":{"line":35,"column":51,"index":963}},"elements":[]}}]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1101,"end":1106,"loc":{"start":{"line":39,"column":44,"index":1101},"end":{"line":39,"column":49,"index":1106}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/trigger'
    },
  'watch': {
      name: 'watch',
      description: 'Watch a pipeline run until completion',
      options: {
        'id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Run ID (defaults to latest run in this repo)', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'interval': { type: 'z.coerce.number.int.positive.default', required: true, hasDefault: true, default: 15, description: 'Polling interval in seconds', short: 't', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":589,"end":591,"loc":{"start":{"line":22,"column":64,"index":589},"end":{"line":22,"column":66,"index":591}},"extra":{"rawValue":15,"raw":"15"},"value":15}}]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON on completion', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":716,"end":721,"loc":{"start":{"line":26,"column":44,"index":716},"end":{"line":26,"column":49,"index":721}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/watch'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
