// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import List from '../src/commands/list.js'
import Open from '../src/commands/open.js'
import Runs from '../src/commands/runs.js'
import Show from '../src/commands/show.js'
import Trigger from '../src/commands/trigger.js'
import Watch from '../src/commands/watch.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['list', 'open', 'runs', 'show', 'trigger', 'watch'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'list': List,
  'open': Open,
  'runs': Runs,
  'show': Show,
  'trigger': Trigger,
  'watch': Watch
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'list': {
      name: 'list',
      description: 'List pipelines, optionally filtered by glob',
      options: {
        'filter': { type: 'z.array.default', required: true, hasDefault: true, default: undefined, description: 'Glob filter on pipeline name (repeatable)', short: 'f', isArray: true, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"ArrayExpression","start":490,"end":492,"loc":{"start":{"line":18,"column":47,"index":490},"end":{"line":18,"column":49,"index":492}},"elements":[]}}]}, validator: '(val) => true' },
        'top': { type: 'z.coerce.number.int.positive.default', required: true, hasDefault: true, default: 1000, description: 'Maximum number of pipelines to fetch', short: 'n', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":646,"end":650,"loc":{"start":{"line":22,"column":59,"index":646},"end":{"line":22,"column":63,"index":650}},"extra":{"rawValue":1000,"raw":"1000"},"value":1000}}]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":784,"end":789,"loc":{"start":{"line":26,"column":44,"index":784},"end":{"line":26,"column":49,"index":789}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/list'
    },
  'open': {
      name: 'open',
      description: 'Open a pipeline run in browser',
      options: {
        'id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Run ID (opens latest for repo when omitted)', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":567,"end":572,"loc":{"start":{"line":14,"column":44,"index":567},"end":{"line":14,"column":49,"index":572}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/open'
    },
  'runs': {
      name: 'runs',
      description: 'List recent pipeline runs for this repository',
      options: {
        'top': { type: 'z.coerce.number.int.positive.default', required: true, hasDefault: true, default: 10, description: 'Maximum number of runs to print', short: 'n', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":545,"end":547,"loc":{"start":{"line":19,"column":59,"index":545},"end":{"line":19,"column":61,"index":547}},"extra":{"rawValue":10,"raw":"10"},"value":10}}]}, validator: '(val) => true' },
        'all': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Include runs from all repositories', short: 'a', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":675,"end":680,"loc":{"start":{"line":23,"column":43,"index":675},"end":{"line":23,"column":48,"index":680}},"value":false}}]}, validator: '(val) => true' },
        'branch': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Filter by branch', short: 'b', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'result': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Filter by result (succeeded/failed/canceled)', short: 'r', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'status': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Filter by status (inProgress/completed/notStarted)', short: 's', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1222,"end":1227,"loc":{"start":{"line":39,"column":44,"index":1222},"end":{"line":39,"column":49,"index":1227}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/runs'
    },
  'show': {
      name: 'show',
      description: 'Show details for a pipeline run',
      options: {
        'id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Pipeline run ID', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":643,"end":648,"loc":{"start":{"line":23,"column":44,"index":643},"end":{"line":23,"column":49,"index":648}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/show'
    },
  'trigger': {
      name: 'trigger',
      description: 'Queue a new pipeline run',
      options: {
        'id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Pipeline definition ID', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'name': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Pipeline definition name', short: 'm', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'branch': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Branch name or full ref', short: 'b', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'parameter': { type: 'z.array.default', required: true, hasDefault: true, default: undefined, description: 'Pipeline parameter key=value (repeatable)', short: 'p', isArray: true, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"ArrayExpression","start":882,"end":884,"loc":{"start":{"line":31,"column":50,"index":882},"end":{"line":31,"column":52,"index":884}},"elements":[]}}]}, validator: '(val) => true' },
        'variable': { type: 'z.array.default', required: true, hasDefault: true, default: undefined, description: 'Pipeline variable key=value (repeatable)', short: 'v', isArray: true, schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"ArrayExpression","start":1028,"end":1030,"loc":{"start":{"line":35,"column":49,"index":1028},"end":{"line":35,"column":51,"index":1030}},"elements":[]}}]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1168,"end":1173,"loc":{"start":{"line":39,"column":44,"index":1168},"end":{"line":39,"column":49,"index":1173}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/trigger'
    },
  'watch': {
      name: 'watch',
      description: 'Watch a pipeline run until completion',
      options: {
        'id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Run ID (defaults to latest run in this repo)', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'interval': { type: 'z.coerce.number.int.positive.default', required: true, hasDefault: true, default: 15, description: 'Polling interval in seconds', short: 't', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":698,"end":700,"loc":{"start":{"line":24,"column":64,"index":698},"end":{"line":24,"column":66,"index":700}},"extra":{"rawValue":15,"raw":"15"},"value":15}}]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON on completion', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":825,"end":830,"loc":{"start":{"line":28,"column":44,"index":825},"end":{"line":28,"column":49,"index":830}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/watch'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
