// This file was automatically generated by Bunli.
// You should NOT make any changes in this file as it will be overwritten.

import type { Command, CLI, GeneratedOptionMeta, RegisteredCommands, CommandOptions, GeneratedCommandMeta } from '@bunli/core'
import { createGeneratedHelpers, registerGeneratedStore } from '@bunli/core'

import Close from '../src/commands/close.js'
import Create from '../src/commands/create.js'
import List from '../src/commands/list.js'
import Recent from '../src/commands/recent.js'
import Show from '../src/commands/show.js'
import Start from '../src/commands/start.js'

// Narrow list of command names to avoid typeof-cycles in types
const names = ['close', 'create', 'list', 'recent', 'show', 'start'] as const
type GeneratedNames = typeof names[number]

const modules: Record<GeneratedNames, Command<any>> = {
  'close': Close,
  'create': Create,
  'list': List,
  'recent': Recent,
  'show': Show,
  'start': Start
} as const

const metadata: Record<GeneratedNames, GeneratedCommandMeta> = {
  'close': {
      name: 'close',
      description: 'Close a task',
      options: {
        'id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Task ID', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":575,"end":580,"loc":{"start":{"line":21,"column":44,"index":575},"end":{"line":21,"column":49,"index":580}},"value":false}}]}, validator: '(val) => true' },
        'completed': { type: 'z.coerce.number.nonnegative.optional', required: false, hasDefault: false, description: 'Completed work hours (also sets remaining to 0)', short: 'c', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' }
      },
      path: './src/commands/close'
    },
  'create': {
      name: 'create',
      description: 'Create an Azure DevOps task',
      options: {
        'parent': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Parent work item ID (Story/Epic)', short: 'p', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'team': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Team name for active iteration lookup', short: 't', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'estimate': { type: 'z.coerce.number.nonnegative.optional', required: false, hasDefault: false, description: 'Original estimate hours', short: 'e', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'remaining': { type: 'z.coerce.number.nonnegative.optional', required: false, hasDefault: false, description: 'Remaining work hours', short: 'r', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'completed': { type: 'z.coerce.number.nonnegative.optional', required: false, hasDefault: false, description: 'Completed work hours', short: 'c', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1339,"end":1344,"loc":{"start":{"line":48,"column":44,"index":1339},"end":{"line":48,"column":49,"index":1344}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/create'
    },
  'list': {
      name: 'list',
      description: 'List sprint tasks or child tasks under a parent item',
      options: {
        'parent': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Parent work item ID (list child tasks)', short: 'p', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'team': { type: 'z.string.trim.optional', required: false, hasDefault: false, description: 'Team name for current sprint lookup', short: 't', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'all': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Include non-active states', short: 'a', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":915,"end":920,"loc":{"start":{"line":38,"column":43,"index":915},"end":{"line":38,"column":48,"index":920}},"value":false}}]}, validator: '(val) => true' },
        'top': { type: 'z.coerce.number.int.positive.default', required: true, hasDefault: true, default: 50, description: 'Maximum number of tasks to print', short: 'n', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":1058,"end":1060,"loc":{"start":{"line":42,"column":59,"index":1058},"end":{"line":42,"column":61,"index":1060}},"extra":{"rawValue":50,"raw":"50"},"value":50}}]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1190,"end":1195,"loc":{"start":{"line":46,"column":44,"index":1190},"end":{"line":46,"column":49,"index":1195}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/list'
    },
  'recent': {
      name: 'recent',
      description: 'List your recent tasks',
      options: {
        'all': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Include closed and non-active states', short: 'a', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":650,"end":655,"loc":{"start":{"line":28,"column":43,"index":650},"end":{"line":28,"column":48,"index":655}},"value":false}}]}, validator: '(val) => true' },
        'top': { type: 'z.coerce.number.int.positive.default', required: true, hasDefault: true, default: 10, description: 'Maximum number of tasks to print', short: 't', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"NumericLiteral","start":804,"end":806,"loc":{"start":{"line":32,"column":59,"index":804},"end":{"line":32,"column":61,"index":806}},"extra":{"rawValue":10,"raw":"10"},"value":10}}]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":936,"end":941,"loc":{"start":{"line":36,"column":44,"index":936},"end":{"line":36,"column":49,"index":941}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/recent'
    },
  'show': {
      name: 'show',
      description: 'Show a task and parent hierarchy',
      options: {
        'id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Task ID', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'parents': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: true, description: 'Include parent hierarchy (Task -> Story -> Epic)', short: 'p', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":726,"end":730,"loc":{"start":{"line":34,"column":47,"index":726},"end":{"line":34,"column":51,"index":730}},"value":true}}]}, validator: '(val) => true' },
        'allow-non-task': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Allow non-task root items (Bug/Story/etc)', short: 'n', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":888,"end":893,"loc":{"start":{"line":38,"column":56,"index":888},"end":{"line":38,"column":61,"index":893}},"value":false}}]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":1032,"end":1037,"loc":{"start":{"line":42,"column":44,"index":1032},"end":{"line":42,"column":49,"index":1037}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/show'
    },
  'start': {
      name: 'start',
      description: 'Start a task',
      options: {
        'id': { type: 'z.coerce.number.int.positive.optional', required: false, hasDefault: false, description: 'Task ID', short: 'i', schema: {"type":"zod","method":"optional","args":[]}, validator: '(val) => true' },
        'json': { type: 'z.coerce.boolean.default', required: true, hasDefault: true, default: false, description: 'Print machine-readable JSON', short: 'j', schema: {"type":"zod","method":"default","args":[{"type":"unknown","raw":{"type":"BooleanLiteral","start":575,"end":580,"loc":{"start":{"line":21,"column":44,"index":575},"end":{"line":21,"column":49,"index":580}},"value":false}}]}, validator: '(val) => true' }
      },
      path: './src/commands/start'
    }
} as const

export const generated = registerGeneratedStore(createGeneratedHelpers(modules, metadata))

export const commands = generated.commands
export const commandMeta = generated.metadata

export interface GeneratedCLI {
  register(cli?: CLI<any>): GeneratedCLI
  list(): Array<{
    name: GeneratedNames
    command: (typeof modules)[GeneratedNames]
    metadata: (typeof metadata)[GeneratedNames]
  }>
  get<Name extends GeneratedNames>(name: Name): (typeof modules)[Name]
  getMetadata<Name extends GeneratedNames>(name: Name): (typeof metadata)[Name]
  getFlags<Name extends keyof RegisteredCommands & string>(name: Name): CommandOptions<Name>
  getFlagsMeta<Name extends GeneratedNames>(name: Name): Record<string, GeneratedOptionMeta>
  withCLI(cli: CLI<any>): { execute(name: string, options: unknown): Promise<void> }
}

export const cli: GeneratedCLI = {
  register: (cliInstance?: CLI<any>) => { generated.register(cliInstance); return cli },
  list: () => generated.list(),
  get: <Name extends GeneratedNames>(name: Name) => generated.get(name),
  getMetadata: <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name),
  getFlags: <Name extends keyof RegisteredCommands & string>(name: Name) => generated.getFlags(name) as CommandOptions<Name>,
  getFlagsMeta: <Name extends GeneratedNames>(name: Name) => generated.getFlagsMeta(name),
  withCLI: (cliInstance) => generated.withCLI(cliInstance)
}

// Enhanced helper functions
export const listCommands = () => generated.list().map(c => c.name)
export const getCommandApi = <Name extends GeneratedNames>(name: Name) => generated.getMetadata(name)
export const getTypedFlags = <Name extends GeneratedNames>(name: Name) => generated.getFlags(name) as CommandOptions<Name>
export const validateCommand = <Name extends GeneratedNames>(name: Name, flags: Record<string, unknown>) => generated.validateCommand(name, flags)
export const findCommandByName = <Name extends GeneratedNames>(name: Name) => generated.findByName(name)
export const findCommandsByDescription = (searchTerm: string) => generated.findByDescription(searchTerm)
export const getCommandNames = () => generated.getCommandNames()

// Auto-register on import for zero-config usage
export default cli

// Ensure module augmentation happens on import
declare module '@bunli/core' {
  // Precise key mapping without typeof cycles
  interface RegisteredCommands extends Record<GeneratedNames, Command<any>> {}
}
